### PR TITLE
Fix player showing twice in 2v2 MGE defeat message

### PR DESCRIPTION
**Pull request by twistedduck**
This should close issue https://github.com/Lange/MGEMod/issues/36

`killer_teammate ` was always returning `SLOT_TWO` as `killer_teammate` was undefined.

This meant that `SLOT_TWO` was being used twice.

I tested on a local server and it seemed to work fine.

I've not commited a binary as I assume you will want to recompile.

### CODE REVIEW

**Comment by Lange** [comment]
LGTM, thanks!

**Comment by WakaFlocka432** [comment]
Using the latest version it's still not fixed the name still gets duplicated

**Comment by twistedduck** [comment]
I did test this and I'm pretty sure the fix works.

On which arena was it erroring? The logic is a little different on normal 2v2 vs bball

If it's still happening I'll test it again and see if I can fix it

**Comment by WakaFlocka432** [comment]
> I did test this and I'm pretty sure the fix works.
> 
> On which arena was it erroring? The logic is a little different on normal 2v2 vs bball
> 
> If it's still happening I'll test it again and see if I can fix it

I set Gran Mid to 2 vs 2 =and it happens when blue team defeats red team i think red team defeating blue teams works fine however this time it repeated my name twice instead of showing the winner as the loser
Eg {GPG} Waka Flocka Flame and {GPG} Waka Flocka Flame (Score:20) defeats Olitude and Lucario Batfoxkid (Score:1) in duel to 20 on Granary Middle [2 vs 2] to test this put "4player" "1" in any map and win the match you'll see the error test both teams red defeating blue and blue defeating red i remember it occurs on blue defeating red

**Pull request merged**
