### PR TITLE
Fix "Query failed: Column count doesnt match value count at row 1" error

### PR DESCRIPTION
**Pull request by AcidZ3r0**
Fix query and compile plugin.

### CODE REVIEW

**Comment by Cprice1771** [comment]
Can you increment the minor version number to 2.0.9.4? otherwise LGTM

**Comment by AcidZ3r0** [comment]
Done.

**Comment by Lange** [comment]
@Cprice1771 if you're able to merge this before I can get around to it, can you re-compile before merging? As a regular security practice, I try to never accept binaries compiled by third parties, just in case.

Ty!

**Comment by Cprice1771** [comment]
@Lange done, I compiled it with the latest source mod compiler though so I hope that's okay.

**Comment by Lange** [comment]
@Cprice1771 yes that should be fine, thank you!

**Pull request merged**
